<?php

/**
 * @file
 * Implements hooks and callbacks for this module.
 */

/**
 * Implements hook_postprocess_bibutils_convert().
 *
 * Cleans the MODS output from Bibutils.
 */
function bibutils_postprocess_bibutils_convert($src, $src_format, $dest, $dest_format) {
  if ($dest_format == 'MODS') {
    return Bibutils::CleanModsFile($dest);
  }
  return TRUE;
}

/**
 * Implements hook_menu().
 */
function bibutils_menu() {
  $items = array();

  $items['admin/islandora/solution_pack_config/scholar/bibutils'] = array(
    'title' => 'Bibutils',
    'description' => 'Configure bibutils executable paths.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bibutils_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
