CREATE DATABASE isle_ld CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'isle_ld_user'@'%' IDENTIFIED BY 'isle_ld_db2018';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, EXECUTE, LOCK TABLES, REFERENCES, SHOW VIEW, TRIGGER ON isle_ld.* TO 'isle_ld_user'@'%';
FLUSH PRIVILEGES;
