<?php
/**
 * @file
 * Include ALL the files in this module.
 */

module_load_include('inc', 'php_lib', 'Array');
module_load_include('inc', 'php_lib', 'Backtrace');
module_load_include('inc', 'php_lib', 'DOMHelpers');
module_load_include('inc', 'php_lib', 'ReadOnlyMembers');
module_load_include('inc', 'php_lib', 'ReflectionHelpers');
module_load_include('inc', 'php_lib', 'String');
module_load_include('inc', 'php_lib', 'File');
