<?php

/**
 * @file
 * Handles the creation/display of islandora:sp-pdf objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_pdf_menu() {
  return array(
    'admin/islandora/solution_pack_config/pdf' => array(
      'title' => 'PDF Solution Pack',
      'description' => 'Define ingest behavior and configure preview display.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_pdf_admin'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_pdf_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_pdf' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-pdf',
      'pattern' => 'islandora_pdf__',
      'variables' => array('islandora_object' => NULL),
    ),
    'islandora_pdf_print' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-pdf-print',
      'pattern' => 'islandora_pdf_print__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_pdf_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_pdf');
  // PDF Content Model.
  $pdf_content_model = $connection->repository->constructObject('islandora:sp_pdf');
  $pdf_content_model->owner = 'fedoraAdmin';
  $pdf_content_model->label = 'Islandora PDF Content Model';
  $pdf_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $pdf_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_pdf_ds_composite_model.xml", FALSE);
  $pdf_content_model->ingestDatastream($datastream);
  // PDF Collection.
  $pdf_collection = $connection->repository->constructObject('islandora:sp_pdf_collection');
  $pdf_collection->owner = 'fedoraAdmin';
  $pdf_collection->label = 'PDF Collection';
  $pdf_collection->models = 'islandora:collectionCModel';
  $pdf_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $pdf_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_pdf_collection_policy.xml", FALSE);
  $pdf_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $pdf_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $pdf_collection->ingestDatastream($datastream);
  return array(
    'islandora_pdf' => array(
      'title' => 'Islandora PDF',
      'objects' => array(
        $pdf_content_model,
        $pdf_collection,
      ),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_pdf_islandora_sp_pdf_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_pdf', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_islandora_view_print_object().
 */
function islandora_pdf_islandora_view_print_object($object) {
  $output = theme('islandora_pdf_print', array('islandora_object' => $object));
  return array('pdf' => $output);
}

/**
 * Implements hook_xml_form_builder_forms().
 */
function islandora_pdf_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_pdf');
  return array(
    'PDF MODS form' => array(
      'form_file' => "$module_path/xml/islandora_pdf_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_xml_form_builder_form_associations().
 */
function islandora_pdf_xml_form_builder_form_associations() {
  return array(
    'islandora_pdf_mods_form' => array(
      'content_model' => 'islandora:sp_pdf',
      'form_name' => 'PDF MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_pdf_islandora_sp_pdf_islandora_ingest_steps() {
  return array(
    'islandora_pdf_file_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_pdf_pdf_upload_form',
      'module' => 'islandora_pdf',
      'file' => 'includes/pdf_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_derivative().
 */
function islandora_pdf_islandora_sp_pdf_islandora_derivative() {
  $derivatives = array();
  $derivatives[] = array(
    'source_dsid' => 'OBJ',
    'destination_dsid' => 'TN',
    'weight' => '0',
    'function' => array(
      'islandora_pdf_add_tn_derivative',
    ),
    'file' => drupal_get_path('module', 'islandora_pdf') . '/includes/derivatives.inc',
  );
  $derivatives[] = array(
    'source_dsid' => 'OBJ',
    'destination_dsid' => 'PREVIEW',
    'weight' => '1',
    'function' => array(
      'islandora_pdf_add_preview_derivative',
    ),
    'file' => drupal_get_path('module', 'islandora_pdf') . '/includes/derivatives.inc',
  );
  if (variable_get('islandora_pdf_create_fulltext', FALSE)) {
    $derivatives[] = array(
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'FULL_TEXT',
      'weight' => '2',
      'function' => array(
        'islandora_pdf_add_fulltext_derivative',
      ),
      'file' => drupal_get_path('module', 'islandora_pdf') . '/includes/derivatives.inc',
    );
  }
  if (variable_get('islandora_pdf_create_pdfa', FALSE)) {
    $derivatives[] = array(
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'PDFA',
      'weight' => '2',
      'function' => array(
        'islandora_pdf_add_pdfa_derivative',
      ),
      'file' => drupal_get_path('module', 'islandora_pdf') . '/includes/derivatives.inc',
    );
  }
  return $derivatives;
}
