---
- name: create ssh directories
  file: path=/home/{{ user_name }}/.ssh owner={{ user_name }} group={{ user_name }} mode=0700 state=directory

- name: set up authorized_keys ONLY FOR ISLANDORA USER
  authorized_key: user={{ user_name }} key="{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ pub_locale }}"

- name: increase ssh timeout
  lineinfile: dest=/etc/ssh/sshd_config line='ClientAliveInterval 60'
