version: '3.7'

#### docker-compose up -d;
## Demo Environment - Used for exploring a full sandboxed ISLE system with an un-themed Islandora / Drupal site.
## Updated 2019-11-25 - Release 1.4.0 (@ 1.4.0)

services:
  isle-portainer: ## Renamed to avoid conflicts on systems/servers with portainer already running.
    image: portainer/portainer
    container_name: isle-portainer-${CONTAINER_SHORT_ID}
    command: -H unix:///var/run/docker.sock --no-auth
    networks:
      - isle-internal
    ports:
      - "9010:9000" ## Remapped to avoid conflicts on systems/servers with portainer already running.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - isle-portainer-data:/data
    labels:
      - traefik.port=9000
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_isle-internal
      ## Enabling access the Portainer interface via traefik is not safe in a production environment unless
      ## you have the ISLE system behind a firewall and, overall, only ports 80 and 443 exposed.
      - traefik.enable=true
      - "traefik.frontend.rule=Host:portainer.${BASE_DOMAIN};"


  mysql:
    image: islandoracollabgroup/isle-mysql:1.4.0
    container_name: isle-mysql-${CONTAINER_SHORT_ID}
    env_file:
      - demo.env
    networks:
      - isle-internal
    ## (Optional): Uncomment to open up the MySQL service on its standard port. Use behind a firewall and do not expose this port publicly.
    ## For the demo or local environments, change the first 3306 to 9306 if an additional MySQL server is being run locally to avoid port conflict.
    #ports:
    #  - "3306:3306"
    volumes:
    ## Customization: Allows for additional tuning of MySQL.
      - ./config/mysql/ISLE.cnf:/etc/mysql/mysql.conf.d/ISLE.cnf
      - isle-db-data:/var/lib/mysql


  fedora:
    image: islandoracollabgroup/isle-fedora:1.4.0
    container_name: isle-fedora-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=768M
      - JAVA_MIN_MEM=128M
    env_file:
      - demo.env
    networks:
      - isle-internal
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - solr
    volumes:
      - isle-fedora-datastreamStore:/usr/local/fedora/data/datastreamStore # (Optional) Migrators can change this to your local DS folder instead of using a Docker volume.
      - isle-fedora-objectStore:/usr/local/fedora/data/objectStore # (Optional) Migrators can change this to your local OS folder instead of using a Docker volume.
      - isle-fedora-resourceIndex:/usr/local/fedora/data/resourceIndex # (Optional) Migrators can change this to your local RI folder instead of using a Docker volume.
      - isle-fedora-activemq:/usr/local/fedora/data/activemq-data # (Optional) Migrators can change this to your local MQ folder instead of using a Docker volume.
      - isle-fedora-XACML:/usr/local/fedora/data/fedora-xacml-policies


  solr:
    image: islandoracollabgroup/isle-solr:1.4.0
    container_name: isle-solr-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=512M
      - JAVA_MIN_MEM=0
    env_file:
      - demo.env
    networks:
      - isle-internal
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    volumes:
      - isle-solr-data:/usr/local/solr


  image-services:
    image: islandoracollabgroup/isle-imageservices:1.4.0
    container_name: isle-images-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=512M
      - JAVA_MIN_MEM=0
    env_file:
      - demo.env
    networks:
      - isle-internal
    depends_on:
      - apache
      - fedora
    ports:
      - "8083:8080"
    labels:
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_isle-internal
      ## Making image-services accessible via traefik is not safe and not recommended
      - traefik.enable=false
      - "traefik.frontend.rule=Host:images.${BASE_DOMAIN}; PathPrefix: /, /cantaloupe"


  apache:
    image: islandoracollabgroup/isle-apache:1.4.0
    container_name: isle-apache-${CONTAINER_SHORT_ID}
    env_file:
      - .env
      - demo.env
    networks:
      isle-internal:
    depends_on:
      - mysql
      - fedora
      - solr
      - traefik
    volumes:
      - isle-apache-data:/var/www/html
      ## (Optional): Uncomment line below to allow bind mounting of the php.ini file for editing of php memory, upload and max_post values.
      #- ./config/apache/php_ini/php.demo.ini:/etc/php/7.1/apache2/php.ini
    labels:
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_isle-internal
      - traefik.enable=true
      - "traefik.frontend.rule=Host:${BASE_DOMAIN}; PathPrefix: /, /cantaloupe"


  traefik:
    image: traefik:1.7.9
    container_name: isle-proxy-${CONTAINER_SHORT_ID}
    networks:
      isle-internal:
      isle-external:
    env_file:
      - demo.env
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/proxy/ssl-certs:/certs:ro
      - ./config/proxy/traefik.demo.toml:/etc/traefik/traefik.toml
    labels:
      - traefik.port=8080
      ## Enabling access to the Traefik interface is not safe in a production environment unless you have the
      ## ISLE system behind a firewall and only ports 80 and 443 exposed.
      - traefik.enable=true
      - traefik.frontend.rule=Host:admin.${BASE_DOMAIN};


# Start - Blazegraph service section
## (Optional-component): Uncomment lines below to run ISLE with the Blazegraph triplestore instead of default Mulgara

#  isle-blazegraph:
#    image: islandoracollabgroup/isle-blazegraph:1.4.0
#    container_name: isle-blazegraph-${CONTAINER_SHORT_ID}
#    environment:
#      - JAVA_MAX_MEM=4096M
#      - JAVA_MIN_MEM=1024M
#    env_file:
#      - demo.env
#    networks:
#      - isle-internal
#    ports:
#      - "8084:8080"
#    volumes:
#      - isle-blazegraph-data:/var/bigdata

# END - Blazegraph service section


# Defined networks
networks:
  isle-internal:
  isle-external:


volumes:
  isle-db-data:
  isle-solr-data:
  isle-apache-data:
  isle-portainer-data:
  isle-fedora-datastreamStore:
  isle-fedora-objectStore:
  isle-fedora-resourceIndex:
  isle-fedora-activemq:
  isle-fedora-XACML:
  ## (Optional component): Uncomment line below to run ISLE with the Blazegraph triplestore instead of default Mulgara
  #isle-blazegraph-data:
