version: '3'

#### docker-compose up -d;
## Updated 2019-03-27 - Release 1.1.1 (@ 1.1.1)

services:

  mysql:
    # build:
    #   context: ../images/isle-mysql
    image: islandoracollabgroup/isle-mysql:1.1.1 # TODO: maybe remove numbers
    container_name: isle-mysql-${CONTAINER_SHORT_ID}
    # environment:
    #   - MYSQL_ROOT_PASSWORD
    env_file:
      - local.env
    networks:
      - isle-internal
    volumes:
      - isle-db-data:/var/lib/mysql
      - isle-mysql-log:/var/log/mysql

  fedora:
    # build:
    #   context: ../images/isle-fedora
    image: islandoracollabgroup/isle-fedora:1.1.1
    container_name: isle-fedora-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=768M
      - JAVA_MIN_MEM=128M
    env_file:
      - local.env
    networks:
      - isle-internal
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - solr
    volumes:
      - isle-fedora-datastreamStore:/usr/local/fedora/data/datastreamStore # Migrators change this to your local DS folder.
      - isle-fedora-objectStore:/usr/local/fedora/data/objectStore # Migrators change this to your local OS folder.
      - isle-fedora-resourceIndex:/usr/local/fedora/data/resourceIndex # Migrators change this to your local RI folder.
      - isle-fedora-activemq:/usr/local/fedora/data/activemq-data # Migrators change this to your local MQ folder.
      - isle-fedora-XACML:/usr/local/fedora/data/fedora-xacml-policies
      - ./logs/fedora/fcrepo:/usr/local/fedora/server/logs
      - ./logs/fedora/tomcat:/usr/local/tomcat/logs

  solr:
    # build:
    #   context: ../images/isle-solr
    image: islandoracollabgroup/isle-solr:1.1.1
    container_name: isle-solr-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=512M
      - JAVA_MIN_MEM=0
    env_file:
      - local.env
    networks:
      - isle-internal
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    volumes:
      - isle-solr-data:/usr/local/solr
      - ./logs/solr:/usr/local/tomcat/logs

  image-services:
    # build:
    #   context: ../images/isle-imageservices
    image: islandoracollabgroup/isle-imageservices:1.1.1
    container_name: isle-images-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=512M
      - JAVA_MIN_MEM=0
    env_file:
      - local.env
    networks:
      - isle-internal
    depends_on:
      - apache
      - fedora
    ports:
      - "8083:8080"
    volumes:
      - ./logs/imageservices:/usr/local/tomcat/logs
    labels:
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_isle-internal
      - traefik.enable=false
      - "traefik.frontend.rule=Host:images.${BASE_DOMAIN}; PathPrefix: /, /adore-djatoka, /cantaloupe"

  apache:
    # build:
    #   context: ../images/isle-apache
    image: islandoracollabgroup/isle-apache:1.1.1
    container_name: isle-apache-${CONTAINER_SHORT_ID}
    env_file:
      - .env
      - local.env
    networks:
      isle-internal:
    depends_on:
      - mysql
      - fedora
      - solr
      - traefik
    volumes:
      - isle-apache-data:/var/www/html
      - ./logs/apache/httpd:/var/log/apache2
      - ./logs/apache/fits:/var/log/fits
    labels:
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_isle-internal
      - traefik.enable=true
      - "traefik.frontend.rule=Host:${BASE_DOMAIN}; PathPrefix: /, /adore-djatoka, /cantaloupe"

  traefik:
    image: traefik:1.7.9
    container_name: isle-proxy-${CONTAINER_SHORT_ID}
    networks:
      isle-internal:
      isle-external:
    env_file:
      - local.env
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/proxy/ssl-certs:/certs:ro  ## Place certs here.
      - ./config/proxy/traefik.toml:/etc/traefik/traefik.toml  ## Edit line 27, 28 with your cert and key names.
    labels:
      - traefik.port=8080
      - traefik.enable=true  ## NOT SAFE FOR PRODUCTION! ##
      - traefik.frontend.rule=Host:admin.${BASE_DOMAIN};

# Defined networks
networks:
  isle-internal:
  isle-external:

volumes:
  isle-db-data:
  isle-mysql-log:
  isle-solr-data:
  isle-apache-data:
  isle-fedora-datastreamStore:
  isle-fedora-objectStore:
  isle-fedora-resourceIndex:
  isle-fedora-activemq:
  isle-fedora-XACML:
