<?php
/**
 * @file
 * oaDOI Badges
 */

/**
 * Implements hook_menu().
 */
function islandora_oadoi_menu() {
  return array(
    'admin/islandora/tools/badges/oadoi' => array(
      'title' => 'oaDOI',
      'description' => 'Configure oaDOI settings.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_oadoi_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function islandora_oadoi_block_info() {
  return array(
    'islandora_oadoi_badge' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'info' => t('Islandora oaDOI Link'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function islandora_oadoi_block_view($delta = '') {
  module_load_include('inc', 'islandora_badges', 'includes/utilities');
  $to_render = array();

  if ($delta == 'islandora_oadoi_badge') {
    $object = menu_get_object('islandora_object', 2);
    if ($object) {
      // Check CModel against Badges configuration.
      if (islandora_badges_show_for_cmodel($object)) {
        // Check for PDF datastream; only run if PDF does not exist.
        if (!$object['PDF']) {
          $doi = islandora_badges_get_doi($object);
          if ($doi) {
            // Set API endpoint URL
            // @TODO: Add to admin form.
            $url = "https://api.oadoi.org/";
            $request_url = $url . $doi;

            // Make the request and get results!
            $result_json = drupal_http_request($request_url);
            $result_array = json_decode($result_json, TRUE);
            $result_free_url = $result_array['results'][0]['free_fulltext_url'];
          }
        }
      }
    }
  }

  if (isset($result_free_url)) {
    global $base_url;
    // If oaDOI points to the current website, do not display block.
    if (strpos($result_free_url, $base_url) !== 0) {
      $link_text = variable_get('islandora_oadoi_linktext', 'Link to PDF');
      $to_render['content'] = '<div class="oadoi"><a href="' . $result_free_url . '" target="_blank">' . $link_text . '</a></div>';
    }
  }
  return $to_render;
}
