<?php

/**
 * @file
 * A simple editorial workflow for Islandora.
 */

/**
 * Implements hook_menu().
 */
function islandora_simple_workflow_menu() {
  $items = array();
  $items['admin/islandora/tools/simple_workflow/list'] = array(
    'title' => 'Simple Workflow objects',
    'description' => 'List of inactive objects.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_simple_workflow_manage_form'),
    'access arguments' => array('manage inactive objects'),
    'file' => 'includes/manage.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function islandora_simple_workflow_permission() {
  return array(
    'bypass inactive object state' => array(
      'title' => t('Bypass default inactive object state'),
      'description' => t('Islandora Simple Workflow sets ingested objects as active if enabled.'),
    ),
    'manage inactive objects' => array(
      'title' => t('Manage inactive objects'),
      'description' => t('View a list of inactive objects.'),
    ),
  );
}

/**
 * Implements hook_islandora_object_alter().
 */
function islandora_simple_workflow_islandora_object_alter(AbstractObject $object, array &$context) {
  module_load_include('inc', 'islandora', 'includes/utilities');
  if ($context['action'] == 'ingest') {
    $connection = islandora_get_tuque_connection();
    $enabled_solution_packs = module_invoke_all('islandora_required_objects', $connection);
    $system_objects = array();
    foreach ($enabled_solution_packs as $solution_pack_module => $solution_pack_info) {
      foreach ($solution_pack_info['objects'] as $solution_pack_object) {
        $system_objects[] = $solution_pack_object->id;
      }
    }
    if (!in_array($object->id, $system_objects) && !islandora_object_access('bypass inactive object state', $object)) {
      $object->state = 'I';
    }
  }
}
