CREATE DATABASE fedora3 CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'fedora_admin'@'%' IDENTIFIED BY 'newsite_sample_fedora_admin_pw';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, EXECUTE, LOCK TABLES, REFERENCES, SHOW VIEW, TRIGGER ON fedora3.* TO 'fedora_admin'@'%';
FLUSH PRIVILEGES;
