CREATE DATABASE newsite_sample_db CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'newsite_sample_db_user'@'%' IDENTIFIED BY 'newsite_sample_db_pw';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, EXECUTE, LOCK TABLES, REFERENCES, SHOW VIEW, TRIGGER ON newsite_sample_db.* TO 'newsite_sample_db_user'@'%';
FLUSH PRIVILEGES;
