<?php

/**
 * @file
 * Defines the install/uninstall hooks for this module.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_internet_archive_bookreader_uninstall() {
  $variables = array(
    'islandora_internet_archive_bookreader_djatoka_url',
    'islandora_internet_archive_bookreader_compression',
    'islandora_internet_archive_bookreader_ocr_field',
    'islandora_internet_archive_bookreader_ocr_filter_field',
    'islandora_internet_archive_bookreader_solr_result_count',
    'islandora_internet_archive_bookreader_sequence_number',
    'islandora_internet_archive_bookreader_overlay_opacity',
    'islandora_internet_archive_bookreader_default_page_view',
  );
  // Delete the Drupal variables defined by this module.
  array_walk($variables, 'variable_del');
}
