CREATE DATABASE islandora_docker CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'islandora_user'@'%' IDENTIFIED BY 'islandoradockerdb2017';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, EXECUTE, LOCK TABLES, REFERENCES, SHOW VIEW, TRIGGER ON islandora_docker.* TO 'islandora_user'@'%';
FLUSH PRIVILEGES;
