<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_islandora_populator().
 */
function ris_populator_islandora_populator() {
  $items = array();

  $items['ris_populator'] = array(
    'title' => t('RIS Populator'),
    'description' => t('Populate metadata from an RIS record.'),
    'type' => 'inline',
    'form' => array(
      'ris' => array(
        '#type' => 'managed_file',
        '#title' => t('RIS File'),
        '#description' => t('Upload a text file containing an RIS record. If multiple are present in the given file, only the first will be used.'),
        '#upload_validators' => array(
          'file_validate_extensions' => array('txt ris'),
        ),
        '#element_validate' => array(
          'ris_populator_validate_file',
        ),
        '#islandora_plupload_do_not_alter' => TRUE,
      ),
    ),
    'output' => array(
      'MODS' => array(
        'callback' => 'ris_populator_generate_mods',
      ),
    ),
    'files' => array(
      array('inc', 'ris_populator', 'includes/populate'),
    ),
  );

  return $items;
}
