sudo: required
dist: trusty
language: php

matrix:
  include:
   #5.3.3 Ubuntu Precise exceptions
    - php: 5.3.3
      dist: precise
      env: FEDORA_VERSION="3.5"
    - php: 5.3.3
      dist: precise
      env: FEDORA_VERSION="3.6.2"
    - php: 5.3.3
      dist: precise
      env: FEDORA_VERSION="3.7.0"
    - php: 5.3.3
      dist: precise
      env: FEDORA_VERSION="3.8.1"
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
env:
  - FEDORA_VERSION="3.5"
  - FEDORA_VERSION="3.6.2"
  - FEDORA_VERSION="3.7.0"
  - FEDORA_VERSION="3.8.1"

branches:
  only:
    - /^7.x/
before_install: 
  - if [[ $(phpenv version-name) = "5.3.3" ]]; then composer config -g -- disable-tls true && composer config -g -- secure-http false; fi;
  - cd $HOME
  - mkdir javascript
  - git clone -b 7.x git://github.com/Islandora/islandora.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solr_search.git
  - git clone -b 7.x git://github.com/Islandora/islandora_importer.git
  - git clone -b 7.x git://github.com/Islandora/islandora_xacml_editor.git
  - git clone -b 7.x git://github.com/Islandora/islandora_bookmark.git
  - git clone -b 7.x git://github.com/Islandora/islandora_batch.git
  - git clone git://github.com/Islandora/citeproc-php.git
  - export ISLANDORA_DIR=$HOME/islandora
  - export JAVASCRIPT_DIR=$HOME/javascript
  - $HOME/islandora/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
  - ln -s $TRAVIS_BUILD_DIR sites/all/modules/islandora_scholar
  - ln -s $HOME/citeproc-php sites/all/libraries/citeproc-php
  - ln -s $HOME/islandora_solr_search sites/all/modules/islandora_solr_search
  - ln -s $HOME/islandora_importer sites/all/modules/islandora_importer
  - ln -s $HOME/islandora_xacml_editor sites/all/modules/islandora_xacml_editor
  - ln -s $HOME/islandora_bookmark sites/all/modules/islandora_bookmark
  - ln -s $HOME/islandora_batch sites/all/modules/islandora_batch
  - drush cc all
  - drush -u 1 en --yes islandora_scholar bibutils citation_exporter doi_importer islandora_google_scholar islandora_scholar_embargo islandora_bibliography ris_importer endnotexml_importer pmid_importer citeproc csl
before_script:
  # Mysql might time out for long tests, increase the wait timeout.
  - mysql -e 'SET @@GLOBAL.wait_timeout=1200'
  - composer self-update
  - composer require phpunit/phpunit '>=4.8.35|>=5.4.3.,<=5.0'
  - if [[ $(phpenv version-name) = "5.3.3" ]]; then composer --prefer-source install; else composer install; fi;
script:
  - ant -buildfile sites/all/modules/islandora_scholar/build.xml lint
  - sites/all/modules/islandora_scholar/tests/scripts/line_endings.sh sites/all/modules/islandora_scholar
  # XXX: Move the 3rd-party library stuff out of the way, so it doesn't
  # throw warnings from coder.
  - mv $TRAVIS_BUILD_DIR/modules/exporter/lib/tcpdf $HOME
  - find $TRAVIS_BUILD_DIR/modules/pmid/xsl/exslt -iname "*.js" -type f -exec cp --parents -v {} $JAVASCRIPT_DIR \;
  - find $TRAVIS_BUILD_DIR/modules/pmid/xsl/exslt -iname "*.js" -type f -exec rm {} \;
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer --no-empty islandora_scholar
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer --no-empty bibutils
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer --no-empty citation_exporter
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer --no-empty doi_importer
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer --no-empty islandora_google_scholar
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer --no-empty islandora_scholar_embargo
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer --no-empty islandora_bibliography
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer --no-empty ris_importer
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer --no-empty endnotexml_importer
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer --no-empty pmid_importer
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer --no-empty citeproc
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer --no-empty csl
  # XXX: Move the 3rd-party library stuff back in, for tests.
  - mv $HOME/tcpdf $TRAVIS_BUILD_DIR/modules/exporter/lib/
  - cp -Rv $JAVASCRIPT_DIR/* $TRAVIS_BUILD_DIR
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/islandora_scholar
  - vendor/bin/phpunit sites/all/modules/islandora_scholar/modules/citeproc/tests/CSL_Dateparser.test
notifications:
  irc: "irc.freenode.org#islandora"
