---

- name: Apt-get update
  apt: update_cache=yes

- name: Ensure that all host dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - software-properties-common
    - python-software-properties
    - ntp
    - openssh-client
    - rsync
    - curl
    - wget
    - git
    - zip
    - unzip
    - vim
    - nano
    - emacs24-nox
    - htop
    - apt-transport-https
    - ca-certificates

- name: turn off ufw
  ufw: state=disabled

- name: Ensure the ntp service is started and enabled
  service: name=ntp enabled=yes

- name: Add Docker apt/gpg key
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

- name: Add Docker repository for Debian / Ubuntu Systems
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present
    update_cache: yes
