<?php

/**
 * @file
 * An Islandora viewer module using Video.js
 */

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_videojs_islandora_viewer_info() {
  return array(
    'islandora_videojs' => array(
      'label' => t('video.js player'),
      'description' => t('video.js for video.'),
      'callback' => 'islandora_videojs_callback',
      'mimetype' => array('audio/mpeg', 'video/mp4'),
      'configuration' => 'admin/islandora/islandora_viewers/videojs',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function islandora_videojs_menu() {
  return array(
    'admin/islandora/islandora_viewers/videojs' => array(
      'title' => 'Video.js',
      'description' => 'Configure the Video.js viewer.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_videojs_admin'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_videojs_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_videojs' => array(
      'template' => 'theme/islandora-videojs',
      'variables' => array('object' => NULL, 'params' => NULL),
    ),
  );
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_islandora_videojs(array &$variables) {
  $params = $variables['params'];
  $variables['sources'] = array();
  if (isset($params['tn'])) {
    $variables['tn'] = $params['tn'];
  }
  $videojs_path = libraries_get_path("video-js");
  drupal_add_js($videojs_path . "/video.js");
  drupal_add_css($videojs_path . '/video-js.css');
  if (variable_get('islandora_videojs_hls_library', FALSE)) {
    drupal_add_js($videojs_path . "/videojs-contrib-hls.js");
  }
  if (isset($params['sources']) && is_array($params['sources'])) {
    $variables['sources'] = $params['sources'];
  }
  elseif (isset($params['url']) && isset($params['mime'])) {
    $variables['sources'][] = array('url' => $params['url'], 'mime' => $params['mime']);
  }
}

/**
 * Callback function to process audio player.
 *
 * @param array $params
 *   Array with configuration info for the audio player.
 */
function islandora_videojs_callback($params = array()) {
  return theme('islandora_videojs', array('params' => $params));
}
