<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_islandora_populator().
 */
function endnotexml_populator_islandora_populator() {
  $items = array();

  $items['endnotexml_populator'] = array(
    'title' => t('EndNote XML Populator'),
    'description' => t('Populate metadata from an EndNote XML record.'),
    'type' => 'inline',
    'form' => array(
      'endnotexml' => array(
        '#type' => 'managed_file',
        '#title' => t('EndNote XML File'),
        '#description' => t('Upload a text file containing an EndNote XML record. If multiple are present in the given file, only the first will be used.'),
        '#upload_validators' => array(
          'file_validate_extensions' => array('txt xml'),
        ),
        '#element_validate' => array(
          'endnotexml_populator_validate_file',
        ),
        '#islandora_plupload_do_not_alter' => TRUE,
      ),
    ),
    'output' => array(
      'MODS' => array(
        'callback' => 'endnotexml_populator_generate_mods',
      ),
    ),
    'files' => array(
      array('inc', 'endnotexml_populator', 'includes/populate'),
    ),
  );

  return $items;
}
