---

- name: Ensure Docker is installed
  package: name={{ docker_package }} state=latest

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- name: Add the appropriate user to the Docker group to run without sudo
  command: sudo usermod -aG docker {{ docker_user }}
