<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:variable name="iso639-2">
        <xsl:text>aar</xsl:text>
        <xsl:text>abk</xsl:text>
        <xsl:text>ace</xsl:text>
        <xsl:text>ach</xsl:text>
        <xsl:text>ada</xsl:text>
        <xsl:text>ady</xsl:text>
        <xsl:text>afa</xsl:text>
        <xsl:text>afh</xsl:text>
        <xsl:text>afr</xsl:text>
        <xsl:text>ain</xsl:text>
        <xsl:text>aka</xsl:text>
        <xsl:text>akk</xsl:text>
        <xsl:text>alb</xsl:text>
        <xsl:text>ale</xsl:text>
        <xsl:text>alg</xsl:text>
        <xsl:text>alt</xsl:text>
        <xsl:text>amh</xsl:text>
        <xsl:text>ang</xsl:text>
        <xsl:text>anp</xsl:text>
        <xsl:text>apa</xsl:text>
        <xsl:text>ara</xsl:text>
        <xsl:text>arc</xsl:text>
        <xsl:text>arg</xsl:text>
        <xsl:text>arm</xsl:text>
        <xsl:text>arn</xsl:text>
        <xsl:text>arp</xsl:text>
        <xsl:text>art</xsl:text>
        <xsl:text>arw</xsl:text>
        <xsl:text>asm</xsl:text>
        <xsl:text>ast</xsl:text>
        <xsl:text>ath</xsl:text>
        <xsl:text>aus</xsl:text>
        <xsl:text>ava</xsl:text>
        <xsl:text>ave</xsl:text>
        <xsl:text>awa</xsl:text>
        <xsl:text>aym</xsl:text>
        <xsl:text>aze</xsl:text>
        <xsl:text>bad</xsl:text>
        <xsl:text>bai</xsl:text>
        <xsl:text>bak</xsl:text>
        <xsl:text>bal</xsl:text>
        <xsl:text>bam</xsl:text>
        <xsl:text>ban</xsl:text>
        <xsl:text>baq</xsl:text>
        <xsl:text>bas</xsl:text>
        <xsl:text>bat</xsl:text>
        <xsl:text>bej</xsl:text>
        <xsl:text>bel</xsl:text>
        <xsl:text>bem</xsl:text>
        <xsl:text>ben</xsl:text>
        <xsl:text>ber</xsl:text>
        <xsl:text>bho</xsl:text>
        <xsl:text>bih</xsl:text>
        <xsl:text>bik</xsl:text>
        <xsl:text>bin</xsl:text>
        <xsl:text>bis</xsl:text>
        <xsl:text>bla</xsl:text>
        <xsl:text>bnt</xsl:text>
        <xsl:text>tib</xsl:text>
        <xsl:text>bos</xsl:text>
        <xsl:text>bra</xsl:text>
        <xsl:text>bre</xsl:text>
        <xsl:text>btk</xsl:text>
        <xsl:text>bua</xsl:text>
        <xsl:text>bug</xsl:text>
        <xsl:text>bul</xsl:text>
        <xsl:text>bur</xsl:text>
        <xsl:text>byn</xsl:text>
        <xsl:text>cad</xsl:text>
        <xsl:text>cai</xsl:text>
        <xsl:text>car</xsl:text>
        <xsl:text>cat</xsl:text>
        <xsl:text>cau</xsl:text>
        <xsl:text>ceb</xsl:text>
        <xsl:text>cel</xsl:text>
        <xsl:text>cze</xsl:text>
        <xsl:text>cha</xsl:text>
        <xsl:text>chb</xsl:text>
        <xsl:text>che</xsl:text>
        <xsl:text>chg</xsl:text>
        <xsl:text>chi</xsl:text>
        <xsl:text>chk</xsl:text>
        <xsl:text>chm</xsl:text>
        <xsl:text>chn</xsl:text>
        <xsl:text>cho</xsl:text>
        <xsl:text>chp</xsl:text>
        <xsl:text>chr</xsl:text>
        <xsl:text>chu</xsl:text>
        <xsl:text>chv</xsl:text>
        <xsl:text>chy</xsl:text>
        <xsl:text>cmc</xsl:text>
        <xsl:text>cop</xsl:text>
        <xsl:text>cor</xsl:text>
        <xsl:text>cos</xsl:text>
        <xsl:text>cpe</xsl:text>
        <xsl:text>cpf</xsl:text>
        <xsl:text>cpp</xsl:text>
        <xsl:text>cre</xsl:text>
        <xsl:text>crh</xsl:text>
        <xsl:text>crp</xsl:text>
        <xsl:text>csb</xsl:text>
        <xsl:text>cus</xsl:text>
        <xsl:text>wel</xsl:text>
        <xsl:text>cze</xsl:text>
        <xsl:text>dak</xsl:text>
        <xsl:text>dan</xsl:text>
        <xsl:text>dar</xsl:text>
        <xsl:text>day</xsl:text>
        <xsl:text>del</xsl:text>
        <xsl:text>den</xsl:text>
        <xsl:text>ger</xsl:text>
        <xsl:text>dgr</xsl:text>
        <xsl:text>din</xsl:text>
        <xsl:text>div</xsl:text>
        <xsl:text>doi</xsl:text>
        <xsl:text>dra</xsl:text>
        <xsl:text>dsb</xsl:text>
        <xsl:text>dua</xsl:text>
        <xsl:text>dum</xsl:text>
        <xsl:text>dut</xsl:text>
        <xsl:text>dyu</xsl:text>
        <xsl:text>dzo</xsl:text>
        <xsl:text>efi</xsl:text>
        <xsl:text>egy</xsl:text>
        <xsl:text>eka</xsl:text>
        <xsl:text>gre</xsl:text>
        <xsl:text>elx</xsl:text>
        <xsl:text>eng</xsl:text>
        <xsl:text>enm</xsl:text>
        <xsl:text>epo</xsl:text>
        <xsl:text>est</xsl:text>
        <xsl:text>baq</xsl:text>
        <xsl:text>ewe</xsl:text>
        <xsl:text>ewo</xsl:text>
        <xsl:text>fan</xsl:text>
        <xsl:text>fao</xsl:text>
        <xsl:text>per</xsl:text>
        <xsl:text>fat</xsl:text>
        <xsl:text>fij</xsl:text>
        <xsl:text>fil</xsl:text>
        <xsl:text>fin</xsl:text>
        <xsl:text>fiu</xsl:text>
        <xsl:text>fon</xsl:text>
        <xsl:text>fre</xsl:text>
        <xsl:text>fre</xsl:text>
        <xsl:text>frm</xsl:text>
        <xsl:text>fro</xsl:text>
        <xsl:text>frr</xsl:text>
        <xsl:text>frs</xsl:text>
        <xsl:text>fry</xsl:text>
        <xsl:text>ful</xsl:text>
        <xsl:text>fur</xsl:text>
        <xsl:text>gaa</xsl:text>
        <xsl:text>gay</xsl:text>
        <xsl:text>gba</xsl:text>
        <xsl:text>gem</xsl:text>
        <xsl:text>geo</xsl:text>
        <xsl:text>ger</xsl:text>
        <xsl:text>gez</xsl:text>
        <xsl:text>gil</xsl:text>
        <xsl:text>gla</xsl:text>
        <xsl:text>gle</xsl:text>
        <xsl:text>glg</xsl:text>
        <xsl:text>glv</xsl:text>
        <xsl:text>gmh</xsl:text>
        <xsl:text>goh</xsl:text>
        <xsl:text>gon</xsl:text>
        <xsl:text>gor</xsl:text>
        <xsl:text>got</xsl:text>
        <xsl:text>grb</xsl:text>
        <xsl:text>grc</xsl:text>
        <xsl:text>gre</xsl:text>
        <xsl:text>grn</xsl:text>
        <xsl:text>gsw</xsl:text>
        <xsl:text>guj</xsl:text>
        <xsl:text>gwi</xsl:text>
        <xsl:text>hai</xsl:text>
        <xsl:text>hat</xsl:text>
        <xsl:text>hau</xsl:text>
        <xsl:text>haw</xsl:text>
        <xsl:text>heb</xsl:text>
        <xsl:text>her</xsl:text>
        <xsl:text>hil</xsl:text>
        <xsl:text>him</xsl:text>
        <xsl:text>hin</xsl:text>
        <xsl:text>hit</xsl:text>
        <xsl:text>hmn</xsl:text>
        <xsl:text>hmo</xsl:text>
        <xsl:text>scr</xsl:text>
        <xsl:text>hsb</xsl:text>
        <xsl:text>hun</xsl:text>
        <xsl:text>hup</xsl:text>
        <xsl:text>arm</xsl:text>
        <xsl:text>iba</xsl:text>
        <xsl:text>ibo</xsl:text>
        <xsl:text>ice</xsl:text>
        <xsl:text>ido</xsl:text>
        <xsl:text>iii</xsl:text>
        <xsl:text>ijo</xsl:text>
        <xsl:text>iku</xsl:text>
        <xsl:text>ile</xsl:text>
        <xsl:text>ilo</xsl:text>
        <xsl:text>ina</xsl:text>
        <xsl:text>inc</xsl:text>
        <xsl:text>ind</xsl:text>
        <xsl:text>ine</xsl:text>
        <xsl:text>inh</xsl:text>
        <xsl:text>ipk</xsl:text>
        <xsl:text>ira</xsl:text>
        <xsl:text>iro</xsl:text>
        <xsl:text>ice</xsl:text>
        <xsl:text>ita</xsl:text>
        <xsl:text>jav</xsl:text>
        <xsl:text>jbo</xsl:text>
        <xsl:text>jpn</xsl:text>
        <xsl:text>jpr</xsl:text>
        <xsl:text>jrb</xsl:text>
        <xsl:text>kaa</xsl:text>
        <xsl:text>kab</xsl:text>
        <xsl:text>kac</xsl:text>
        <xsl:text>kal</xsl:text>
        <xsl:text>kam</xsl:text>
        <xsl:text>kan</xsl:text>
        <xsl:text>kar</xsl:text>
        <xsl:text>kas</xsl:text>
        <xsl:text>geo</xsl:text>
        <xsl:text>kau</xsl:text>
        <xsl:text>kaw</xsl:text>
        <xsl:text>kaz</xsl:text>
        <xsl:text>kbd</xsl:text>
        <xsl:text>kha</xsl:text>
        <xsl:text>khi</xsl:text>
        <xsl:text>khm</xsl:text>
        <xsl:text>kho</xsl:text>
        <xsl:text>kik</xsl:text>
        <xsl:text>kin</xsl:text>
        <xsl:text>kir</xsl:text>
        <xsl:text>kmb</xsl:text>
        <xsl:text>kok</xsl:text>
        <xsl:text>kom</xsl:text>
        <xsl:text>kon</xsl:text>
        <xsl:text>kor</xsl:text>
        <xsl:text>kos</xsl:text>
        <xsl:text>kpe</xsl:text>
        <xsl:text>krc</xsl:text>
        <xsl:text>krl</xsl:text>
        <xsl:text>kro</xsl:text>
        <xsl:text>kru</xsl:text>
        <xsl:text>kua</xsl:text>
        <xsl:text>kum</xsl:text>
        <xsl:text>kur</xsl:text>
        <xsl:text>kut</xsl:text>
        <xsl:text>lad</xsl:text>
        <xsl:text>lah</xsl:text>
        <xsl:text>lam</xsl:text>
        <xsl:text>lao</xsl:text>
        <xsl:text>lat</xsl:text>
        <xsl:text>lav</xsl:text>
        <xsl:text>lez</xsl:text>
        <xsl:text>lim</xsl:text>
        <xsl:text>lin</xsl:text>
        <xsl:text>lit</xsl:text>
        <xsl:text>lol</xsl:text>
        <xsl:text>loz</xsl:text>
        <xsl:text>ltz</xsl:text>
        <xsl:text>lua</xsl:text>
        <xsl:text>lub</xsl:text>
        <xsl:text>lug</xsl:text>
        <xsl:text>lui</xsl:text>
        <xsl:text>lun</xsl:text>
        <xsl:text>luo</xsl:text>
        <xsl:text>lus</xsl:text>
        <xsl:text>mac</xsl:text>
        <xsl:text>mad</xsl:text>
        <xsl:text>mag</xsl:text>
        <xsl:text>mah</xsl:text>
        <xsl:text>mai</xsl:text>
        <xsl:text>mak</xsl:text>
        <xsl:text>mal</xsl:text>
        <xsl:text>man</xsl:text>
        <xsl:text>mao</xsl:text>
        <xsl:text>map</xsl:text>
        <xsl:text>mar</xsl:text>
        <xsl:text>mas</xsl:text>
        <xsl:text>may</xsl:text>
        <xsl:text>mdf</xsl:text>
        <xsl:text>mdr</xsl:text>
        <xsl:text>men</xsl:text>
        <xsl:text>mga</xsl:text>
        <xsl:text>mic</xsl:text>
        <xsl:text>min</xsl:text>
        <xsl:text>mis</xsl:text>
        <xsl:text>mac</xsl:text>
        <xsl:text>mkh</xsl:text>
        <xsl:text>mlg</xsl:text>
        <xsl:text>mlt</xsl:text>
        <xsl:text>mnc</xsl:text>
        <xsl:text>mni</xsl:text>
        <xsl:text>mno</xsl:text>
        <xsl:text>moh</xsl:text>
        <xsl:text>mol</xsl:text>
        <xsl:text>mon</xsl:text>
        <xsl:text>mos</xsl:text>
        <xsl:text>mao</xsl:text>
        <xsl:text>may</xsl:text>
        <xsl:text>mul</xsl:text>
        <xsl:text>mun</xsl:text>
        <xsl:text>mus</xsl:text>
        <xsl:text>mwl</xsl:text>
        <xsl:text>mwr</xsl:text>
        <xsl:text>bur</xsl:text>
        <xsl:text>myn</xsl:text>
        <xsl:text>myv</xsl:text>
        <xsl:text>nah</xsl:text>
        <xsl:text>nai</xsl:text>
        <xsl:text>nap</xsl:text>
        <xsl:text>nau</xsl:text>
        <xsl:text>nav</xsl:text>
        <xsl:text>nbl</xsl:text>
        <xsl:text>nde</xsl:text>
        <xsl:text>ndo</xsl:text>
        <xsl:text>nds</xsl:text>
        <xsl:text>nep</xsl:text>
        <xsl:text>new</xsl:text>
        <xsl:text>nia</xsl:text>
        <xsl:text>nic</xsl:text>
        <xsl:text>niu</xsl:text>
        <xsl:text>dut</xsl:text>
        <xsl:text>nno</xsl:text>
        <xsl:text>nob</xsl:text>
        <xsl:text>nog</xsl:text>
        <xsl:text>non</xsl:text>
        <xsl:text>nor</xsl:text>
        <xsl:text>nqo</xsl:text>
        <xsl:text>nso</xsl:text>
        <xsl:text>nub</xsl:text>
        <xsl:text>nwc</xsl:text>
        <xsl:text>nya</xsl:text>
        <xsl:text>nym</xsl:text>
        <xsl:text>nyn</xsl:text>
        <xsl:text>nyo</xsl:text>
        <xsl:text>nzi</xsl:text>
        <xsl:text>oci</xsl:text>
        <xsl:text>oji</xsl:text>
        <xsl:text>ori</xsl:text>
        <xsl:text>orm</xsl:text>
        <xsl:text>osa</xsl:text>
        <xsl:text>oss</xsl:text>
        <xsl:text>ota</xsl:text>
        <xsl:text>oto</xsl:text>
        <xsl:text>paa</xsl:text>
        <xsl:text>pag</xsl:text>
        <xsl:text>pal</xsl:text>
        <xsl:text>pam</xsl:text>
        <xsl:text>pan</xsl:text>
        <xsl:text>pap</xsl:text>
        <xsl:text>pau</xsl:text>
        <xsl:text>peo</xsl:text>
        <xsl:text>per</xsl:text>
        <xsl:text>phi</xsl:text>
        <xsl:text>phn</xsl:text>
        <xsl:text>pli</xsl:text>
        <xsl:text>pol</xsl:text>
        <xsl:text>pon</xsl:text>
        <xsl:text>por</xsl:text>
        <xsl:text>pra</xsl:text>
        <xsl:text>pro</xsl:text>
        <xsl:text>pus</xsl:text>
        <xsl:text>qaa</xsl:text>
        <xsl:text>que</xsl:text>
        <xsl:text>raj</xsl:text>
        <xsl:text>rap</xsl:text>
        <xsl:text>rar</xsl:text>
        <xsl:text>roa</xsl:text>
        <xsl:text>roh</xsl:text>
        <xsl:text>rom</xsl:text>
        <xsl:text>rum</xsl:text>
        <xsl:text>rum</xsl:text>
        <xsl:text>run</xsl:text>
        <xsl:text>rup</xsl:text>
        <xsl:text>rus</xsl:text>
        <xsl:text>sad</xsl:text>
        <xsl:text>sag</xsl:text>
        <xsl:text>sah</xsl:text>
        <xsl:text>sai</xsl:text>
        <xsl:text>sal</xsl:text>
        <xsl:text>sam</xsl:text>
        <xsl:text>san</xsl:text>
        <xsl:text>sas</xsl:text>
        <xsl:text>sat</xsl:text>
        <xsl:text>scc</xsl:text>
        <xsl:text>scn</xsl:text>
        <xsl:text>sco</xsl:text>
        <xsl:text>scr</xsl:text>
        <xsl:text>sel</xsl:text>
        <xsl:text>sem</xsl:text>
        <xsl:text>sga</xsl:text>
        <xsl:text>sgn</xsl:text>
        <xsl:text>shn</xsl:text>
        <xsl:text>sid</xsl:text>
        <xsl:text>sin</xsl:text>
        <xsl:text>sio</xsl:text>
        <xsl:text>sit</xsl:text>
        <xsl:text>sla</xsl:text>
        <xsl:text>slo</xsl:text>
        <xsl:text>slo</xsl:text>
        <xsl:text>slv</xsl:text>
        <xsl:text>sma</xsl:text>
        <xsl:text>sme</xsl:text>
        <xsl:text>smi</xsl:text>
        <xsl:text>smj</xsl:text>
        <xsl:text>smn</xsl:text>
        <xsl:text>smo</xsl:text>
        <xsl:text>sms</xsl:text>
        <xsl:text>sna</xsl:text>
        <xsl:text>snd</xsl:text>
        <xsl:text>snk</xsl:text>
        <xsl:text>sog</xsl:text>
        <xsl:text>som</xsl:text>
        <xsl:text>son</xsl:text>
        <xsl:text>sot</xsl:text>
        <xsl:text>spa</xsl:text>
        <xsl:text>alb</xsl:text>
        <xsl:text>srd</xsl:text>
        <xsl:text>srn</xsl:text>
        <xsl:text>scc</xsl:text>
        <xsl:text>srr</xsl:text>
        <xsl:text>ssa</xsl:text>
        <xsl:text>ssw</xsl:text>
        <xsl:text>suk</xsl:text>
        <xsl:text>sun</xsl:text>
        <xsl:text>sus</xsl:text>
        <xsl:text>sux</xsl:text>
        <xsl:text>swa</xsl:text>
        <xsl:text>swe</xsl:text>
        <xsl:text>syr</xsl:text>
        <xsl:text>tah</xsl:text>
        <xsl:text>tai</xsl:text>
        <xsl:text>tam</xsl:text>
        <xsl:text>tat</xsl:text>
        <xsl:text>tel</xsl:text>
        <xsl:text>tem</xsl:text>
        <xsl:text>ter</xsl:text>
        <xsl:text>tet</xsl:text>
        <xsl:text>tgk</xsl:text>
        <xsl:text>tgl</xsl:text>
        <xsl:text>tha</xsl:text>
        <xsl:text>tib</xsl:text>
        <xsl:text>tig</xsl:text>
        <xsl:text>tir</xsl:text>
        <xsl:text>tiv</xsl:text>
        <xsl:text>tkl</xsl:text>
        <xsl:text>tlh</xsl:text>
        <xsl:text>tli</xsl:text>
        <xsl:text>tmh</xsl:text>
        <xsl:text>tog</xsl:text>
        <xsl:text>ton</xsl:text>
        <xsl:text>tpi</xsl:text>
        <xsl:text>tsi</xsl:text>
        <xsl:text>tsn</xsl:text>
        <xsl:text>tso</xsl:text>
        <xsl:text>tuk</xsl:text>
        <xsl:text>tum</xsl:text>
        <xsl:text>tup</xsl:text>
        <xsl:text>tur</xsl:text>
        <xsl:text>tut</xsl:text>
        <xsl:text>tvl</xsl:text>
        <xsl:text>twi</xsl:text>
        <xsl:text>tyv</xsl:text>
        <xsl:text>udm</xsl:text>
        <xsl:text>uga</xsl:text>
        <xsl:text>uig</xsl:text>
        <xsl:text>ukr</xsl:text>
        <xsl:text>umb</xsl:text>
        <xsl:text>und</xsl:text>
        <xsl:text>urd</xsl:text>
        <xsl:text>uzb</xsl:text>
        <xsl:text>vai</xsl:text>
        <xsl:text>ven</xsl:text>
        <xsl:text>vie</xsl:text>
        <xsl:text>vol</xsl:text>
        <xsl:text>vot</xsl:text>
        <xsl:text>wak</xsl:text>
        <xsl:text>wal</xsl:text>
        <xsl:text>war</xsl:text>
        <xsl:text>was</xsl:text>
        <xsl:text>wel</xsl:text>
        <xsl:text>wen</xsl:text>
        <xsl:text>wln</xsl:text>
        <xsl:text>wol</xsl:text>
        <xsl:text>xal</xsl:text>
        <xsl:text>xho</xsl:text>
        <xsl:text>yao</xsl:text>
        <xsl:text>yap</xsl:text>
        <xsl:text>yid</xsl:text>
        <xsl:text>yor</xsl:text>
        <xsl:text>ypk</xsl:text>
        <xsl:text>zap</xsl:text>
        <xsl:text>zen</xsl:text>
        <xsl:text>zha</xsl:text>
        <xsl:text>chi</xsl:text>
        <xsl:text>znd</xsl:text>
        <xsl:text>zul</xsl:text>
        <xsl:text>zun</xsl:text>
        <xsl:text>zxx</xsl:text>
        <xsl:text>zza</xsl:text>
    </xsl:variable>
</xsl:stylesheet>